### ISSUE TITLE
buildkitd did not make connection available after start with error: timeout: buildkitd failed to start (in time)

### ISSUE THREAD

**Issue by arialdomartini** [earthly/earthly#1934]
While trying to figure out how to work around the problem in #1929, I got stuck with the following error.<br/>
That's related to the use of the [earthly/earthly](https://hub.docker.com/r/earthly/earthly) Docker image:

Running the command mentioned in the Quick Start section of the documentation:

```bash
docker run --privileged -t -e NO_DOCKER=1 -v $(pwd):/workspace -v earthly-tmp:/tmp/earthly:rw earthly/earthly:v0.6.14 +for-linux
```

I get:

```
Using tcp://ab67f19b1e5f:8372 as buildkit daemon
loading config values from "/etc/.earthly/config.yml"
auto frontend initialization failed due to failed to autodetect a supported frontend: 2 errors occurred:
	* docker-shell frontend failed to initalize: command failed: docker info: exit status 1: Client:
 Context:    default
 Debug Mode: false

Server:
ERROR: Cannot connect to the Docker daemon at unix:///var/run/docker.sock. Is the docker daemon running?
errors pretty printing info: exit status 1
	* podman-shell frontend failed to initalize: command failed: podman info --format={{.Host.Security.Rootless}}: exec: "podman": executable file not found in $PATH: : exec: "podman": executable file not found in $PATH

; but will try anyway
           bootstrap | Bootstrapping successful.

 1. Init 🚀
————————————————————————————————————————————————————————————————————————————————

Share your logs with an Earthly account (experimental)! Register for one at https://ci.earthly.dev.
Error: build new buildkitd client: connect provided buildkit: timeout 1m0s: buildkitd did not make connection available after start with error: failed to list workers: Unavailable: connection error: desc = "transport: Error while dialing dial tcp 172.17.0.2:8372: connect: connection refused": buildkitd failed to start (in time)
It seems that buildkitd had an issue. You can report crashes at https://github.com/earthly/earthly/issues/new.

================================= System Info ==================================

version: v0.6.14
build-sha: 831d37ee160252d612e6c8cbaf8681e8062f8227
platform: linux/amd64; Linux

================================ Docker Version ================================

&containerutil.FrontendInfo{ClientVersion:"", ClientAPIVersion:"", ClientPlatform:"", ServerVersion:"", ServerAPIVersion:"", ServerPlatform:"", ServerAddress:""}

================================ Buildkit Logs =================================
```

That's my setup:

```bash
$ uname -r
5.18.3-arch1-1

$ docker --version
Docker version 20.10.17, build 100c70180f
```
The same command, just works in Windows WSL. I'm ready to bet that it also used to work days ago on the same Arch Linux where it fails now.

Also, `earthly`, the command, works just fine.

I read in other issues that this might be related to  IpTables. I run:

```bash
sudo modprobe ip_tables
```

I see the following images 

```bash
$ docker images
REPOSITORY        TAG       IMAGE ID       CREATED        SIZE
earthly/earthly   v0.6.14   70dc596b6f28   2 months ago   305MB
```

I tried removing it, and I deleted all the running containers

```bash
docker rm -f `docker ps -aq` && docker image rm `docker images -q`
```

reinstalled both `docker` and `earthly`, and run the command again, but I got the very same message.

I'm scratching my head...

**Comment by vladaionescu** [comment]
Note that despite attempting to clean up everything there is still the volume `earthly-tmp` which remained. This holds the buildkit cache and some WITH DOCKER intermediate files. It's possible that it could be causing an issue. You could try to remove that volume too and restart. (Please note that only one earthly container should access that volume at a time - the buildkit cache wasn't designed to be accessed in parallel by different Buildkit processes.)

(Side note: `docker system prune -a -f --volumes` is a good command for resetting all of Docker stuff, AFTER you have stopped all containers - it won't clean up things that are in use)

If it doesn't work for you after that, we should look at the buildkit logs. The buildkit logs should be located at `/var/log/buildkitd.log` within the container if you wouldn't mind posting those here.

**Comment by arialdomartini** [comment]
Great hint about volumes, I did not think about them.<br/>
I run

```bash
$ docker rm -f `docker ps -aq` && docker image rm `docker images -q`
$ docker system prune -a -f --volumes
Deleted Volumes:
earthly-tmp
8a5802bb6d29d2b81f67f78ceb0373d95cd91654e2001d1f0e4370b1a04ab19d
earthly-cache
```

So, `earthly-cache` is definitely gone.</br>
Unfortunately, the Init phase did not work anyway.<br/>
Let me share with you the logs:

```bash
$ docker ps -a
CONTAINER ID   IMAGE                     COMMAND                  CREATED              STATUS                      PORTS     NAMES
19a7297a15c8   earthly/earthly:v0.6.14   "/usr/bin/earthly-en…"   About a minute ago   Exited (6) 39 seconds ago             lucid_fermi
$ docker exec lucid_fermi cat /var/log/buildkitd.log
Error response from daemon: Container 19a7297a15c8a50126eaa1262007142173bcde0db3c34e543fa29d37c38be47e is not running
$ docker start lucid_fermi
lucid_fermi
$ docker exec lucid_fermi cat /var/log/buildkitd.log
starting earthly-buildkit with EARTHLY_GIT_HASH=831d37ee160252d612e6c8cbaf8681e8062f8227 BUILDKIT_BASE_IMAGE=github.com/earthly/buildkit:f126d5cedf8a91de9948f374b982cce3fb5649f6+build
detected cgroups v2
sh: write error: Resource busy
```

I expected to see more, but this is all the file contains.

(In the meanwhile, I'm using the installed command `earthly`, and it's working just great!<br/>
The idea of building with Earthly having Docker as the sole dependency is very intriguing)

**Comment by vladaionescu** [comment]
Interesting - @alexcb has done some recent work with cgroups2. It might be related.

**Comment by alexcb** [comment]
definitely cgroup v2 related: in the regular case earthly runs `buildkitd/entrypoint.sh` directly, so it ends up with `PID=1`; however, in this case `earthly-entrypoint.sh` is run directly, so it ends up with `PID=1`, it then runs `buildkitd/entrypoint.sh` as a seperate process, which hasn't been granted the same cgroup permissions as `PID=1`. I'll take a deeper look at coming up with a fix.

**Comment by alexcb** [comment]
#1958 fixes this. Additionally, it now performs a check to print a warning if other processes are in the root cgroup which causes the `Resource busy` error.

For users who want to override the entrypoint, they'll need to do something similar to:

```bash
if [ -f "/sys/fs/cgroup/cgroup.controllers" ]; then
    echo "detected cgroups v2; moving pid $$ to subgroup"

    # move the process under a new cgroup to prevent buildkitd/entrypoint.sh
    # from getting a "h: write error: Resource busy" error while enabling controllers
    # via echo +pids > /sys/fs/cgroup/cgroup.subtree_control
    mkdir -p /sys/fs/cgroup/my-entrypoint
    echo "$$" > /sys/fs/cgroup/my-entrypoint/cgroup.procs
fi
```

I'll extend the docs to include a note regarding that.

(on a sidenote, hopefully the above is a generic fix for folks searching for "how to fix `write error: Resource busy` cgroups2 errors)

**Comment by alexcb** [comment]
This fix has been released: https://github.com/earthly/earthly/releases/tag/v0.6.18

**Comment by alexcb** [comment]
#1965 documents the required cgroup setup steps for users creating their own entrypoint script.

**Comment by alexcb** [comment]
@arialdomartini let us know if the latest release works for you, feel free to re-open this if it doesn't. Thanks for reporting the issue.

**Comment by arialdomartini** [comment]
It just works. You are amazing guys!

**Comment by stellarpower** [comment]
I am running Earthly under (rootless) podman; in version 0.7.6 under Jammy Jellyfish, I still see the `sh: write error: Resource busy` error. I think we are now on cgroupsv2, having upgraded from Focal recently where we were limited to v1 for various compatibility issues:
```
$ podman logs earthly-buildkitd
starting earthly-buildkit with EARTHLY_GIT_HASH=78d2f5be89c8ada1048ed7130ed319948bf79912 BUILDKIT_BASE_IMAGE=github.com/earthly/buildkit:0da024053105e3807a23ee7225954d822fabda00+build
detected cgroups v2; buildkit/entrypoint.sh running under pid=1
warning: processes exist in the root cgroup; this may cause errors during cgroup initialization
sh: write error: Resource busy

```
